### ISSUE TITLE
When fn has optional formal parameter, it will pass function type param into fn

### ISSUE THREAD

**Issue by ahungrynoob** [RyanZim/universalify#10]
This line has problem.
https://github.com/RyanZim/universalify/blob/master/index.js#L8

**Comment by ahungrynoob** [comment]
So I have to hack it, like this:
```javascript
function findPackageJson(startDir, callback) {
  // work around for universalify.fromCallback
  // https://github.com/RyanZim/universalify/issues/10
  if (typeof startDir === 'function') {
    callback = startDir;
    startDir = undefined;
  }
  function jumpAndCheckPath(dir, callback) {
    dir = path.join(dir, '..');
    if (dir !== path.resolve(dir, '..')) {
      findPackageJson(dir, callback);
      return;
    }
    callback(undefined, null);
  }
  const dir = path.resolve(startDir || process.cwd());

  const pkgFile = path.join(dir, 'package.json');

  fs.exists(pkgFile, exists => {
    if (!exists) {
      jumpAndCheckPath(dir, callback);
      return;
    }
    fs.stat(pkgFile, (e, stat) => {
      if (e) callback(e);
      if (stat.isFile()) {
        callback(undefined, pkgFile);
        return;
      }
      jumpAndCheckPath(dir, callback);
    });
  });
}
```

**Comment by RyanZim** [comment]
I'm not sure I'm understanding the problem; anytime you have optional parameters for a callback function, you have to check for parameter types to find the callback.

**Comment by ahungrynoob** [comment]
@RyanZim The async function has two optional arguments, when I pass no arguments to it in the runtime, universalify.fromCallback will replace the first argument with:
```javascript
(err, res) => {
          if (err) return reject(err)
          resolve(res)
        }
```

**Comment by RyanZim** [comment]
Yeah, understood; but what would you expect universalify to do? It needs to pass the callback someplace.

**Comment by ahungrynoob** [comment]
The possible way I though of is use regex to match the function string, and get the number of arguments, replace the last argument. But it is still complicated and not elegant. 
May be mention this drawback in read me is enough.

**Comment by RyanZim** [comment]
If you're using a callback-based async function directly, you wouldn't be expected to pass in empty options; this is just normal boilerplate for callback functions.
