### ISSUE TITLE
Why use `Object.defineProperty`?

### ISSUE THREAD

**Issue by niftylettuce** [RyanZim/universalify#7]
Just curious why you're using `Object.defineProperty`?  Great package. cc @omgimalexis

**Comment by RyanZim** [comment]
I forget the exact reasoning, but I think the idea was to prevent odd behavior in cases where something messed with the native function prototype. See http://2ality.com/2012/08/property-definition-assignment.html for details on the differences.

**Comment by niftylettuce** [comment]
Cool, thanks @RyanZim.
