### ISSUE TITLE
Three arguments

### ISSUE THREAD

**Issue by dcousens** [RyanZim/universalify#9]
> universalify does not support calling the callback with more than three arguments

Where does this limit appear?
The limits I found were:

https://github.com/RyanZim/universalify/blob/ab4b5cd7e962c4915da68bdf0e5b8f9aa677f8f6/index.js#L8-L11

That indicates you only support `err` and `res`. eg `(err => res => void)`.

https://github.com/RyanZim/universalify/blob/ab4b5cd7e962c4915da68bdf0e5b8f9aa677f8f6/index.js#L23

And the same here.

**Comment by RyanZim** [comment]
You're correct, those are the only limits.

My point was that universalify doesn't work with things like [`fs.read()`](https://nodejs.org/api/fs.html#fs_fs_read_fd_buffer_offset_length_position_callback), which has a callback with arguments of the form: `(err, bytesRead, buffer)`. For such a case, universalify won't pass the `buffer` argument as part of the promise resolution value.

There's nothing that expressly prevents you from using universalify with such functions if you don't care about the third argument, it's just a warning that universalify won't handle the third argument.

**Comment by dcousens** [comment]
Ok.  So it is a typo? `s/three/two`? Or have I miscount?

**Comment by RyanZim** [comment]
Ah, yes, it's a typo in the docs, and I totally misread it here as well. Should read:

> universalify does not support calling the callback with three or more arguments
